# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160412_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('karma', models.IntegerField()),
            ],
        ),
    ]
