# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-15 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
